### ISSUE TITLE
Rollup.config.js file Update

### ISSUE THREAD

**Issue by lonexw** [Lockstep-Network/lockstep-sdk-typescript#17]
Hello, I learned something from your tech articles. 

https://medium.com/codex/bundling-a-typescript-library-for-node-with-rollup-js-2c8add5e736f

this repo may be need some update to work normally.  it need install **[@rollup/plugin-node-resolve](https://www.npmjs.com/package/@rollup/plugin-node-resolve)**  plugin to solve some module dependencies problem:

```
// rollup.config.js
import resolve from '@rollup/plugin-node-resolve';
...
plugins: [resolve(), typescript()]
```

**Comment by tspence** [comment]
Thanks for reaching out! 

Does this problem affect consumers of the package, or only the package building process?  I'll ask the team to help verify this change.

That said, this looks solid.  Would you be willing to submit this as a pull request, please?

**Comment by tspence** [comment]
Believed resolved with https://github.com/lonexw/lockstep-sdk-typescript/commit/d7f66d1cb14efb5bff7505caa5f5e787e04e7edc - Thank you so much for this contribution!

This code will ship with the Week 11 SDK that goes out in a few days.
